### PR TITLE
Colorize it!

### PR DESCRIPTION
**Pull request by TheoBrigitte**
What about bringing some color to luigi's output ?

I am using this since few days now and really enjoy it, so I thought I should share.
Here is what it looks like in pratice:
screen shot 2018-03-15 at 13 09 17

It is just a ruff idea, it might be nice to add support for `-no-color` flag and easier color customisation

### CODE REVIEW

**Comment by kopiczko** [comment]
BTW does it still pass tests?

**Comment by kopiczko** [comment]
BTW does it still pass tests?

Adding `-no-color` should be easy it could just replace

```
+
+var (
+	black   = color.New(color.FgBlack).SprintFunc()
+	red     = color.New(color.FgRed).SprintFunc()
+	green   = color.New(color.FgGreen).SprintFunc()
+	yellow  = color.New(color.FgYellow).SprintFunc()
+	blue    = color.New(color.FgBlue).SprintFunc()
+	magenta = color.New(color.FgMagenta).SprintFunc()
+	cyan    = color.New(color.FgCyan).SprintFunc()
+	white   = color.New(color.FgWhite).SprintFunc()
+
+	separator = red(" | ")
 )
```

**Comment by TheoBrigitte** [comment]
Added `-no-color` flag to disable colorized output. It just disable colorized output on a global level in the color library. No need for extra effort.
Added `-color` flag to force colorized output when using pipes. It takes precedence over `-no-color`

Test still pass! The color library has a builtin mechanism to disable colors when no tty is detected
see https://github.com/fatih/color/blob/15a760a2b268fb5aa0677c8f0604a8bb9e7579b2/color.go#L16

**Comment by TheoBrigitte** [comment]
Flags are used and disable color at global level within the color package

https://github.com/giantswarm/luigi/pull/2/files#diff-7ddfb3e035b42cd70649cc33393fe32cR18


Also copy pasting works great here, using iterm on osx

**Pull request merged**
